name: churn_platform
version: "1.0.0"
config-version: 2

profile: churn_platform

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  churn_platform:
    staging:
      +materialized: view
    marts:
      +materialized: table
