"""
Step 1.2 — profile every column of every raw table: row count, null rate,
distinct count, min/max, top 10 values. Written as a script rather than a
one-off manual query per column so it's rerunnable against any load of the
data, and so the profile itself is reviewable in a diff.

Outputs notebooks/01_data_profile.md.
"""

import os
from pathlib import Path

import psycopg2

DB_DSN = os.environ.get("CHURN_DB_DSN", "host=localhost port=5432 dbname=churn user=churn password=churn")
OUT_PATH = Path(__file__).resolve().parent.parent / "notebooks" / "01_data_profile.md"

TABLES = ["members", "transactions", "user_logs", "ground_truth_membership"]


def get_columns(cur, table):
    cur.execute("""
        SELECT column_name, data_type
        FROM information_schema.columns
        WHERE table_name = %s
        ORDER BY ordinal_position
    """, (table,))
    return cur.fetchall()


def profile_column(cur, table, column, dtype):
    cur.execute(f'SELECT count(*), count("{column}"), count(DISTINCT "{column}") FROM {table}')
    total, non_null, distinct = cur.fetchone()
    null_count = total - non_null
    null_rate = null_count / total if total else 0

    min_val = max_val = None
    if dtype in ("integer", "smallint", "numeric", "double precision", "date", "timestamp without time zone"):
        cur.execute(f'SELECT min("{column}"), max("{column}") FROM {table}')
        min_val, max_val = cur.fetchone()

    cur.execute(f'''
        SELECT "{column}", count(*) AS n
        FROM {table}
        GROUP BY "{column}"
        ORDER BY n DESC
        LIMIT 10
    ''')
    top10 = cur.fetchall()

    return {
        "column": column, "dtype": dtype, "total": total,
        "null_count": null_count, "null_rate": null_rate,
        "distinct": distinct, "min": min_val, "max": max_val, "top10": top10,
    }


def render_table_section(table, profiles):
    lines = [f"## `{table}`\n"]
    lines.append("| column | type | rows | null_count | null_rate | distinct | min | max |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for p in profiles:
        lines.append(
            f"| {p['column']} | {p['dtype']} | {p['total']:,} | {p['null_count']:,} | "
            f"{p['null_rate']:.2%} | {p['distinct']:,} | {p['min']} | {p['max']} |"
        )
    lines.append("")
    for p in profiles:
        lines.append(f"**Top 10 values — `{table}.{p['column']}`**\n")
        lines.append("| value | count |")
        lines.append("|---|---|")
        for val, n in p["top10"]:
            lines.append(f"| {val} | {n:,} |")
        lines.append("")
    return "\n".join(lines)


def main():
    conn = psycopg2.connect(DB_DSN)
    sections = ["# Data profile\n\nGenerated by `sql/profile_tables.py`. One row per column: "
                "count, null rate, distinct count, min/max, and top 10 values.\n"]
    try:
        with conn.cursor() as cur:
            for table in TABLES:
                print(f"Profiling {table}...")
                cols = get_columns(cur, table)
                profiles = [profile_column(cur, table, col, dtype) for col, dtype in cols]
                sections.append(render_table_section(table, profiles))
    finally:
        conn.close()

    OUT_PATH.parent.mkdir(exist_ok=True)
    OUT_PATH.write_text("\n".join(sections))
    print(f"Written to {OUT_PATH}")


if __name__ == "__main__":
    main()
